// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubastaYa.Infrastructure.Persistence;

#nullable disable

namespace SubastaYa.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SubastaYaDbContext))]
    partial class SubastaYaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SubastaYa.Domain.Entities.AuditoriaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetalleJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditoriaLogs");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("SaldoRetenido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Billeteras");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlIcono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Tecnología",
                            UrlIcono = "https://example.com/icon-tech.png"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Vehículos",
                            UrlIcono = "https://example.com/icon-car.png"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Coleccionables",
                            UrlIcono = "https://example.com/icon-collect.png"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Indumentaria",
                            UrlIcono = "https://example.com/icon-clothes.png"
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Puja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPuja")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubastaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("SubastaId");

                    b.ToTable("Pujas");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Subasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GanadorUsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("IncrementoMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontoFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PujaLiderId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("GanadorUsuarioId");

                    b.HasIndex("PujaLiderId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Subastas");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.TransaccionLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BilleteraId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SubastaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BilleteraId");

                    b.HasIndex("SubastaId");

                    b.ToTable("TransaccionesLedger");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.AuditoriaLog", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Billetera", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Billetera")
                        .HasForeignKey("SubastaYa.Domain.Entities.Billetera", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Puja", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Usuario", "Comprador")
                        .WithMany("Pujas")
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entities.Subasta", "Subasta")
                        .WithMany("Pujas")
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Subasta", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Subastas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entities.Usuario", "GanadorUsuario")
                        .WithMany()
                        .HasForeignKey("GanadorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SubastaYa.Domain.Entities.Puja", "PujaLider")
                        .WithMany()
                        .HasForeignKey("PujaLiderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SubastaYa.Domain.Entities.Usuario", "Vendedor")
                        .WithMany("SubastasPublicadas")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("GanadorUsuario");

                    b.Navigation("PujaLider");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.TransaccionLedger", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Billetera", "Billetera")
                        .WithMany("Movimientos")
                        .HasForeignKey("BilleteraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entities.Subasta", "Subasta")
                        .WithMany()
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Billetera");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Billetera", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Subastas");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Subasta", b =>
                {
                    b.Navigation("Pujas");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Billetera");

                    b.Navigation("Pujas");

                    b.Navigation("SubastasPublicadas");
                });
#pragma warning restore 612, 618
        }
    }
}
